version: "3"

services:
  rabbit:
    image: rabbitmq
    container_name: rabbit

  send:
    build: ./send
    volumes:
     - ./send:/app

  receive:
    build: ./receive
    volumes:
     - ./receive:/app

  web:
    build: ./web
    ports:
      - "8080:8080"
    volumes:
    - ./web:/app

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
