version: "3"

services:
  rabbit:
    image: rabbitmq

  send:
    build: ./send
    volumes:
     - ./send:/app

  receive:
    build: ./receive
    volumes:
     - ./receive:/app

  web:
    build: ./web
    volumes:
    - ./webview:app


